# Generated by Django 2.0.7 on 2018-07-07 10:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
