# Generated by Django 2.0.7 on 2018-07-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20180707_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
