# Generated by Django 2.0.7 on 2018-07-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_auto_20180707_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form',
            name='require_update',
            field=models.BooleanField(default=False),
        ),
    ]
