# Generated by Django 2.0.7 on 2018-07-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_auto_20180708_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
