# Generated by Django 2.0.7 on 2018-07-09 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_auto_20180709_1533'),
        ('configuration', '0005_auto_20180709_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ManyToManyField(to='nodes.Node')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.Service')),
            ],
        ),
    ]
