# Generated by Django 2.0.7 on 2018-07-12 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0006_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField()),
                ('state', models.CharField(choices=[('STARTING', 'Starting up'), ('COMMUNICATING', 'Communiticating with device'), ('READY', 'Ready for commit'), ('DONE', 'Configuration Committed'), ('FAIL', 'Configuration Failed')], max_length=255)),
                ('diff', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.Service')),
            ],
        ),
    ]
