# Generated by Django 2.0.7 on 2018-07-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180710_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
