# Generated by Django 2.0.7 on 2018-07-10 11:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
