# Generated by Django 2.0.7 on 2018-07-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='enable_password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
