# Generated by Django 2.0.7 on 2018-07-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_auto_20180704_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='driver',
            field=models.CharField(choices=[('eos', 'Arista EOS'), ('junos', 'Juniper JUNOS'), ('iosxr', 'Cisco IOS-XR'), ('nxos', 'Cisco NXOS'), ('ios', 'Cisco IOS')], max_length=255),
        ),
    ]
