# Generated by Django 2.0.7 on 2018-07-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0006_auto_20180710_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='hostname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
