# Generated by Django 2.0.7 on 2018-07-31 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0009_auto_20180731_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodes.Site'),
        ),
    ]
