# Generated by Django 2.0.7 on 2018-07-31 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0010_auto_20180731_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('enabled', models.BooleanField()),
                ('speed', models.IntegerField(null=True)),
                ('mac_address', models.CharField(max_length=255, null=True)),
                ('source', models.CharField(choices=[('napalm', 'NAPALM'), ('manual', 'MANUAL')], max_length=255)),
                ('discovered', models.DateTimeField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.Node')),
            ],
        ),
    ]
